# Generated by Django 5.1.6 on 2026-04-05 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pgimage',
            name='pg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pgs.pg'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='pg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgs.pg'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
