# Generated by Django 5.1.6 on 2026-04-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
