# Generated by Django 5.1.6 on 2026-04-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0003_pg_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pg',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
