# Generated by Django 5.1.6 on 2026-04-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0004_pg_owner_email_pg_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
