# Generated by Django 5.1.6 on 2026-04-05 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgs.pg')),
            ],
        ),
    ]
